version: 2

builds:
  - id: "ragx"
    main: ./cmd/ragx
    binary: ragx
    goos:
      - linux
    ldflags:
      - -X main.Version={{ if .IsSnapshot }}{{ .Version }}{{ else }}{{ .Tag }}{{ end }}

snapshot:
  version_template: "{{ .Version }}-devel+{{ .ShortCommit }}"

archives:
  - id: "ragx"
    name_template: "ragx_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

    files:
      - UNLICENSE

    ids: [ragx]
    formats: [tar.gz]
